sudo: false

language: python

python:
  - 2.7

before_install: cd tests

install:
  - sudo pip install conda
  - sudo conda init
  - while read requirement; do conda install --yes $requirement; done < requirements.txt
  - pip install codecov

script:
  - coverage run tests.py

after_success:
  - codecov